title: Sylvite
description: The natural way to use the KCL
about: The natural way to use the KCL
disqus_shortname:
google_analytics:
urls:
    - text: About
      url: /
      icon: fa-home
      layout: post
    - text: Usage
      url: /usage/
      icon: fa-book
    - text: Configuration
      url: /configuration/
      icon: fa-cogs
    - text: Protocol
      url: /protocol/
      icon: fa-info-circle
    - text: Download
      url: https://github.com/empiricalresults/sylvite/releases/download/0.0.5/sylvite-0.0.5.jar
      icon: fa-download
    - text: Github
      url: https://github.com/empiricalresults/sylvite
      icon: fa-github

enableTags: true
tagarray: []

baseurl: "/sylvite"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
